name: Save Message

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: '匿名'
      message:
        description: 'Message'
        required: true

jobs:
  save_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current messages
        run: |
          if [ ! -f messages.json ]; then
            echo '[]' > messages.json
          fi

      - name: Add new message
        run: |
          node -e "
          const fs = require('fs');
          const messages = JSON.parse(fs.readFileSync('messages.json'));
          messages.push({ name: '${{ github.event.inputs.name }}', message: '${{ github.event.inputs.message }}' });
          fs.writeFileSync('messages.json', JSON.stringify(messages, null, 2));
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add messages.json
          git commit -m 'Add new message'
          git push
