name: Submit Message

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the user'
        required: false
        default: 'Anonymous'
      message:
        description: 'Message content'
        required: true

jobs:
  submit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update messages.json
        run: |
          # Create a JSON object from the inputs
          MESSAGE_JSON=$(jq -n \
            --arg name "${{ github.event.inputs.name }}" \
            --arg message "${{ github.event.inputs.message }}" \
            --arg timestamp "$(date --utc +%Y-%m-%dT%H:%M:%SZ)" \
            '{name: $name, message: $message, timestamp: $timestamp}')
          
          # Read the current messages.json
          CURRENT_MESSAGES=$(curl -s https://raw.githubusercontent.com/LINMOH/LINMOH.github.io/main/messages.json)

          # Append the new message to the existing messages
          UPDATED_MESSAGES=$(echo $CURRENT_MESSAGES | jq ". += [$MESSAGE_JSON]")

          # Save the updated JSON to the file
          echo $UPDATED_MESSAGES | jq . > messages.json

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add new message"
          add: "messages.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
