name: Handle New Message

on:
  repository_dispatch:
    types: [new-message]

jobs:
  update_message_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Append message to messages.json
      run: |
        echo "Appending new message to messages.json"
        echo "[{
          \"name\": \"${{ github.event.client_payload.name }}\",
          \"message\": \"${{ github.event.client_payload.message }}\"
        }]" >> messages.json
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add messages.json
        git commit -m "Add new message"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
